### PR TITLE
Lib only

### PR DESCRIPTION
**Pull request by jackm97**
On Unix systems, switching everything to lower case makes directories with upper case un-openable

### CODE REVIEW

**Comment by aiekick** [comment]
the conversion in lower case is just for search. normally there is no impact on files or directory behavior
the last times i tested that on linux/osx it was working. so since this moment maybe there is a bug
 but the solution is not to desactivate that thing.

**Comment by jackm97** [comment]
Without this change, all files are displayed lower case in the file dialog box and I can't access the case sensitive folder/file names. I see what you mean about how this would affect the search functionality, but since unix systems are case sensitive is this a problem when it comes to searching? This was admittedly a quick fix for me and probably should've looked a little more closely before doing a pull request. I can look a little deeper and see if I can fix it without affecting search functionality. Want to close this pull request?

Also, this is the only ImGui file explorer that has "just worked" for me on Ubuutnu (except for this bug) so thanks for writing a great extension!

**Comment by aiekick** [comment]
thanks.

the lowercase trick is definitely required for the search, (the normal way is more hard, and due to the realttime need many modifications).
btw he cant be a problem for the rest of the behavior.

i will analyze on my debian

just to be sure, the issue is all the files are displayed lowercase so you cant see what is the good file lower or upper case ?
and/or you can't open directory or validate file ?

**Comment by jackm97** [comment]
I actually figured it out. The OptimizeFilenameForSearchOperations method takes the string by reference so you're not only setting infos.filename_optimized, you're also changing infos.filename. Passing the string by value fixes the problem for me and search functionality behaves as expected

**Comment by aiekick** [comment]
haha nice. i was sure, it could be a refactor issue :) thanks for pointing that. you can modify your PL with this change ?
thanks again

**Comment by aiekick** [comment]
you have merged master in Lib_Only. i will do the correction no problem

**Comment by jackm97** [comment]
Yeah I'm running on low sleep haha. My bad I was just about to fix but if you're going to do it I'm just going to close this. Glad I could help

**Comment by aiekick** [comment]
thanks you very mush. btw

just a question you are using the last C api or the base C++ api ?

**Comment by jackm97** [comment]
Of course! C++ api

**Comment by aiekick** [comment]
commit done :) thanks for your help

**Comment by jackm97** [comment]
you're welcome. thanks for the extension

**Pull request closed without merging**
