### PR TITLE
UTF8 fixes for 'std::filesystem' version of `IFileSystem`

### PR DESCRIPTION
**Pull request by m9710797**
As discussed in:
    https://github.com/aiekick/ImGuiFileDialog/issues/170

Big caveat: I tried to be careful in creating this PR, but I was NOT able to test or even compile this code on Windows!

Please read the commit message for lots more details.

### CODE REVIEW

**Comment by aiekick** [comment]
thanks will check and try to test that

**Comment by m9710797** [comment]
Hi.
No problem if you didn't have time yet. But since there hasn't been any activity on this PR for a week, I wanted to give this a ping.

**Comment by aiekick** [comment]
Hi,
i not see any improvement since i guess i have no font with the extra symbols.
btw, yes its not my priority at this moment.
You know IGFD is maintained on my spare time, and since im not paid for work on it, its not my priority regarding paid projects. 
btw, its not an issue here, since, the IFilesystem  purpose, is to let the user use its own fs. 
so you can apply your modification yourself. 
Btw in your case its strange to propsoe a cross platfom software so with user on winwdows who have a but but no dev on windows to fix it. you know you can install a vm with win10 on  linux on it (even a trial version of windows)

**Comment by m9710797** [comment]
Hi. I was now able to test this PR on a windows machine. And I can confirm it fixes the bug.

**Pull request merged**
